/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author Miguel
 */
public class Check_In extends javax.swing.JFrame {

    /**
     * Creates new form Check_In
     */
    public Check_In() {
        initComponents();
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
       this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTiposP1 = new javax.swing.ButtonGroup();
        buttonGroupSencillasP1 = new javax.swing.ButtonGroup();
        buttonGroupDobleP1 = new javax.swing.ButtonGroup();
        buttonGroupTripleP1 = new javax.swing.ButtonGroup();
        jLabelPiso1 = new javax.swing.JLabel();
        jLabelPiso2 = new javax.swing.JLabel();
        jCheckBoxSencilla = new javax.swing.JCheckBox();
        jCheckBoxDoble = new javax.swing.JCheckBox();
        jCheckBoxTriple = new javax.swing.JCheckBox();
        jCheckBoxSencilla2 = new javax.swing.JCheckBox();
        jCheckBoxDoble2 = new javax.swing.JCheckBox();
        jCheckBoxTriple2 = new javax.swing.JCheckBox();
        jCheckBoxHab101 = new javax.swing.JCheckBox();
        jCheckBoxHab102 = new javax.swing.JCheckBox();
        jCheckBoxHab103 = new javax.swing.JCheckBox();
        jCheckBoxHab104 = new javax.swing.JCheckBox();
        jCheckBoxHab105 = new javax.swing.JCheckBox();
        jCheckBoxHab106 = new javax.swing.JCheckBox();
        jCheckBoxHab107 = new javax.swing.JCheckBox();
        jCheckBoxHab108 = new javax.swing.JCheckBox();
        jCheckBoxHab109 = new javax.swing.JCheckBox();
        jCheckBoxHab110 = new javax.swing.JCheckBox();
        jCheckBoxHab111 = new javax.swing.JCheckBox();
        jCheckBoxHab112 = new javax.swing.JCheckBox();
        jCheckBoxHab113 = new javax.swing.JCheckBox();
        jCheckBoxHab114 = new javax.swing.JCheckBox();
        jCheckBoxHab115 = new javax.swing.JCheckBox();
        jButtonMusic = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPiso1.setText("Piso 1");

        jLabelPiso2.setText("Piso 2");

        buttonGroupTiposP1.add(jCheckBoxSencilla);
        jCheckBoxSencilla.setText("Sencilla");
        jCheckBoxSencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSencillaActionPerformed(evt);
            }
        });

        buttonGroupTiposP1.add(jCheckBoxDoble);
        jCheckBoxDoble.setText("Doble");
        jCheckBoxDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDobleActionPerformed(evt);
            }
        });

        buttonGroupTiposP1.add(jCheckBoxTriple);
        jCheckBoxTriple.setText("Triple");
        jCheckBoxTriple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTripleActionPerformed(evt);
            }
        });

        jCheckBoxSencilla2.setText("Sencilla");
        jCheckBoxSencilla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSencilla2ActionPerformed(evt);
            }
        });

        jCheckBoxDoble2.setText("Doble");
        jCheckBoxDoble2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDoble2ActionPerformed(evt);
            }
        });

        jCheckBoxTriple2.setText("Triple");

        buttonGroupSencillasP1.add(jCheckBoxHab101);
        jCheckBoxHab101.setText("101");

        buttonGroupSencillasP1.add(jCheckBoxHab102);
        jCheckBoxHab102.setText("102");

        buttonGroupSencillasP1.add(jCheckBoxHab103);
        jCheckBoxHab103.setText("103");

        buttonGroupSencillasP1.add(jCheckBoxHab104);
        jCheckBoxHab104.setText("104");

        buttonGroupSencillasP1.add(jCheckBoxHab105);
        jCheckBoxHab105.setText("105");

        buttonGroupSencillasP1.add(jCheckBoxHab106);
        jCheckBoxHab106.setText("106");

        buttonGroupDobleP1.add(jCheckBoxHab107);
        jCheckBoxHab107.setText("107");

        buttonGroupDobleP1.add(jCheckBoxHab108);
        jCheckBoxHab108.setText("108");

        buttonGroupDobleP1.add(jCheckBoxHab109);
        jCheckBoxHab109.setText("109");

        buttonGroupDobleP1.add(jCheckBoxHab110);
        jCheckBoxHab110.setText("110");

        buttonGroupDobleP1.add(jCheckBoxHab111);
        jCheckBoxHab111.setText("111");

        buttonGroupTripleP1.add(jCheckBoxHab112);
        jCheckBoxHab112.setText("112");

        buttonGroupTripleP1.add(jCheckBoxHab113);
        jCheckBoxHab113.setText("113");

        buttonGroupTripleP1.add(jCheckBoxHab114);
        jCheckBoxHab114.setText("114");

        buttonGroupTripleP1.add(jCheckBoxHab115);
        jCheckBoxHab115.setText("115");

        jButtonMusic.setText("Music");

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPiso2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPiso1)
                                    .addComponent(jCheckBoxSencilla)
                                    .addComponent(jCheckBoxDoble)
                                    .addComponent(jCheckBoxTriple))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab101)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab107)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab112))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab102)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab108)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab113))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab103)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab109)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab114))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab104)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab110)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab115))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab105)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab111))
                                    .addComponent(jCheckBoxHab106)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxDoble2)
                                    .addComponent(jCheckBoxTriple2)
                                    .addComponent(jCheckBoxSencilla2))))
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelPiso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxSencilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxDoble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxTriple))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab101)
                            .addComponent(jCheckBoxHab107)
                            .addComponent(jCheckBoxHab112))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab102)
                            .addComponent(jCheckBoxHab108)
                            .addComponent(jCheckBoxHab113))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab103)
                            .addComponent(jCheckBoxHab109)
                            .addComponent(jCheckBoxHab114))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab104)
                            .addComponent(jCheckBoxHab110)
                            .addComponent(jCheckBoxHab115))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab105)
                            .addComponent(jCheckBoxHab111))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxHab106)
                .addGap(18, 18, 18)
                .addComponent(jLabelPiso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxSencilla2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDoble2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTriple2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMusic)
                    .addComponent(jButtonRegresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSencillaActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(true);
       this.jCheckBoxHab102.setVisible(true);
       this.jCheckBoxHab103.setVisible(true);
       this.jCheckBoxHab104.setVisible(true);
       this.jCheckBoxHab105.setVisible(true);
       this.jCheckBoxHab106.setVisible(true);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
        this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
    }//GEN-LAST:event_jCheckBoxSencillaActionPerformed

    private void jCheckBoxDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDobleActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(true);
       this.jCheckBoxHab108.setVisible(true);
       this.jCheckBoxHab109.setVisible(true);
       this.jCheckBoxHab110.setVisible(true);
       this.jCheckBoxHab111.setVisible(true);
       this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
    }//GEN-LAST:event_jCheckBoxDobleActionPerformed

    private void jCheckBoxTripleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTripleActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
       this.jCheckBoxHab112.setVisible(true);
       this.jCheckBoxHab113.setVisible(true);
       this.jCheckBoxHab114.setVisible(true);
       this.jCheckBoxHab115.setVisible(true);
    }//GEN-LAST:event_jCheckBoxTripleActionPerformed

    private void jCheckBoxDoble2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDoble2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDoble2ActionPerformed

    private void jCheckBoxSencilla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSencilla2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSencilla2ActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal abrir=new MenuPrincipal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDobleP1;
    private javax.swing.ButtonGroup buttonGroupSencillasP1;
    private javax.swing.ButtonGroup buttonGroupTiposP1;
    private javax.swing.ButtonGroup buttonGroupTripleP1;
    private javax.swing.JButton jButtonMusic;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JCheckBox jCheckBoxDoble;
    private javax.swing.JCheckBox jCheckBoxDoble2;
    private javax.swing.JCheckBox jCheckBoxHab101;
    private javax.swing.JCheckBox jCheckBoxHab102;
    private javax.swing.JCheckBox jCheckBoxHab103;
    private javax.swing.JCheckBox jCheckBoxHab104;
    private javax.swing.JCheckBox jCheckBoxHab105;
    private javax.swing.JCheckBox jCheckBoxHab106;
    private javax.swing.JCheckBox jCheckBoxHab107;
    private javax.swing.JCheckBox jCheckBoxHab108;
    private javax.swing.JCheckBox jCheckBoxHab109;
    private javax.swing.JCheckBox jCheckBoxHab110;
    private javax.swing.JCheckBox jCheckBoxHab111;
    private javax.swing.JCheckBox jCheckBoxHab112;
    private javax.swing.JCheckBox jCheckBoxHab113;
    private javax.swing.JCheckBox jCheckBoxHab114;
    private javax.swing.JCheckBox jCheckBoxHab115;
    private javax.swing.JCheckBox jCheckBoxSencilla;
    private javax.swing.JCheckBox jCheckBoxSencilla2;
    private javax.swing.JCheckBox jCheckBoxTriple;
    private javax.swing.JCheckBox jCheckBoxTriple2;
    private javax.swing.JLabel jLabelPiso1;
    private javax.swing.JLabel jLabelPiso2;
    // End of variables declaration//GEN-END:variables
}
