/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;




/**
 *
 * @author Miguel
 */
public class Check_In extends javax.swing.JFrame {

    /**
     * Creates new form Check_In
     */
        // FondoPanel fondo=new FondoPanel();
    public Check_In() {
        
   
        initComponents();
     // this.setContentPane(fondo);
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
       this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
       this.jCheckBoxHab116.setVisible(false);
       this.jCheckBoxHab117.setVisible(false);
       this.jCheckBoxHab118.setVisible(false);
       this.jCheckBoxHab119.setVisible(false);
       this.jCheckBoxHab120.setVisible(false);
       this.jCheckBoxHab121.setVisible(false);
       this.jCheckBoxHab122.setVisible(false);
       this.jCheckBoxHab123.setVisible(false);
       this.jCheckBoxHab124.setVisible(false);
       this.jCheckBoxHab125.setVisible(false);
       this.jCheckBoxHab126.setVisible(false);
       this.jCheckBoxHab127.setVisible(false);
       this.jCheckBoxHab128.setVisible(false);
       this.jCheckBoxHab129.setVisible(false);
       this.jCheckBoxHab130.setVisible(false);
       this.jPanelDisp.setVisible(false);
       this.jPanelOcup.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTiposP1 = new javax.swing.ButtonGroup();
        buttonGroupSencillasP1 = new javax.swing.ButtonGroup();
        buttonGroupDobleP1 = new javax.swing.ButtonGroup();
        buttonGroupTripleP1 = new javax.swing.ButtonGroup();
        buttonGroupTiposP2 = new javax.swing.ButtonGroup();
        buttonGroupSencillasP2 = new javax.swing.ButtonGroup();
        buttonGroupDoblesP2 = new javax.swing.ButtonGroup();
        buttonGroupTripleP2 = new javax.swing.ButtonGroup();
        jLabelPiso1 = new javax.swing.JLabel();
        jLabelPiso2 = new javax.swing.JLabel();
        jCheckBoxSencilla = new javax.swing.JCheckBox();
        jCheckBoxDoble = new javax.swing.JCheckBox();
        jCheckBoxTriple = new javax.swing.JCheckBox();
        jCheckBoxSencilla2 = new javax.swing.JCheckBox();
        jCheckBoxDoble2 = new javax.swing.JCheckBox();
        jCheckBoxTriple2 = new javax.swing.JCheckBox();
        jCheckBoxHab101 = new javax.swing.JCheckBox();
        jCheckBoxHab102 = new javax.swing.JCheckBox();
        jCheckBoxHab103 = new javax.swing.JCheckBox();
        jCheckBoxHab104 = new javax.swing.JCheckBox();
        jCheckBoxHab105 = new javax.swing.JCheckBox();
        jCheckBoxHab106 = new javax.swing.JCheckBox();
        jCheckBoxHab107 = new javax.swing.JCheckBox();
        jCheckBoxHab108 = new javax.swing.JCheckBox();
        jCheckBoxHab109 = new javax.swing.JCheckBox();
        jCheckBoxHab110 = new javax.swing.JCheckBox();
        jCheckBoxHab111 = new javax.swing.JCheckBox();
        jCheckBoxHab112 = new javax.swing.JCheckBox();
        jCheckBoxHab113 = new javax.swing.JCheckBox();
        jCheckBoxHab114 = new javax.swing.JCheckBox();
        jCheckBoxHab115 = new javax.swing.JCheckBox();
        jButtonMusic = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jCheckBoxHab116 = new javax.swing.JCheckBox();
        jCheckBoxHab117 = new javax.swing.JCheckBox();
        jCheckBoxHab118 = new javax.swing.JCheckBox();
        jCheckBoxHab119 = new javax.swing.JCheckBox();
        jCheckBoxHab120 = new javax.swing.JCheckBox();
        jCheckBoxHab121 = new javax.swing.JCheckBox();
        jCheckBoxHab122 = new javax.swing.JCheckBox();
        jCheckBoxHab123 = new javax.swing.JCheckBox();
        jCheckBoxHab124 = new javax.swing.JCheckBox();
        jCheckBoxHab125 = new javax.swing.JCheckBox();
        jCheckBoxHab126 = new javax.swing.JCheckBox();
        jCheckBoxHab127 = new javax.swing.JCheckBox();
        jCheckBoxHab128 = new javax.swing.JCheckBox();
        jCheckBoxHab129 = new javax.swing.JCheckBox();
        jCheckBoxHab130 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelDisp = new javax.swing.JPanel();
        jPanelOcup = new javax.swing.JPanel();
        jButtonRentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPiso1.setText("Piso 1");

        jLabelPiso2.setText("Piso 2");

        buttonGroupTiposP1.add(jCheckBoxSencilla);
        jCheckBoxSencilla.setText("Sencilla");
        jCheckBoxSencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSencillaActionPerformed(evt);
            }
        });

        buttonGroupTiposP1.add(jCheckBoxDoble);
        jCheckBoxDoble.setText("Doble");
        jCheckBoxDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDobleActionPerformed(evt);
            }
        });

        buttonGroupTiposP1.add(jCheckBoxTriple);
        jCheckBoxTriple.setText("Triple");
        jCheckBoxTriple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTripleActionPerformed(evt);
            }
        });

        buttonGroupTiposP2.add(jCheckBoxSencilla2);
        jCheckBoxSencilla2.setText("Sencilla");
        jCheckBoxSencilla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSencilla2ActionPerformed(evt);
            }
        });

        buttonGroupTiposP2.add(jCheckBoxDoble2);
        jCheckBoxDoble2.setText("Doble");
        jCheckBoxDoble2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDoble2ActionPerformed(evt);
            }
        });

        buttonGroupTiposP2.add(jCheckBoxTriple2);
        jCheckBoxTriple2.setText("Triple");
        jCheckBoxTriple2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTriple2ActionPerformed(evt);
            }
        });

        buttonGroupSencillasP1.add(jCheckBoxHab101);
        jCheckBoxHab101.setText("101");
        jCheckBoxHab101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHab101ActionPerformed(evt);
            }
        });

        buttonGroupSencillasP1.add(jCheckBoxHab102);
        jCheckBoxHab102.setText("102");

        buttonGroupSencillasP1.add(jCheckBoxHab103);
        jCheckBoxHab103.setText("103");

        buttonGroupSencillasP1.add(jCheckBoxHab104);
        jCheckBoxHab104.setText("104");

        buttonGroupSencillasP1.add(jCheckBoxHab105);
        jCheckBoxHab105.setText("105");

        buttonGroupSencillasP1.add(jCheckBoxHab106);
        jCheckBoxHab106.setText("106");
        jCheckBoxHab106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHab106ActionPerformed(evt);
            }
        });

        buttonGroupDobleP1.add(jCheckBoxHab107);
        jCheckBoxHab107.setText("107");

        buttonGroupDobleP1.add(jCheckBoxHab108);
        jCheckBoxHab108.setText("108");

        buttonGroupDobleP1.add(jCheckBoxHab109);
        jCheckBoxHab109.setText("109");

        buttonGroupDobleP1.add(jCheckBoxHab110);
        jCheckBoxHab110.setText("110");

        buttonGroupDobleP1.add(jCheckBoxHab111);
        jCheckBoxHab111.setText("111");

        buttonGroupTripleP1.add(jCheckBoxHab112);
        jCheckBoxHab112.setText("112");

        buttonGroupTripleP1.add(jCheckBoxHab113);
        jCheckBoxHab113.setText("113");

        buttonGroupTripleP1.add(jCheckBoxHab114);
        jCheckBoxHab114.setText("114");

        buttonGroupTripleP1.add(jCheckBoxHab115);
        jCheckBoxHab115.setText("115");

        jButtonMusic.setText("Music");

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        buttonGroupSencillasP2.add(jCheckBoxHab116);
        jCheckBoxHab116.setText("116");

        buttonGroupSencillasP2.add(jCheckBoxHab117);
        jCheckBoxHab117.setText("117");

        buttonGroupSencillasP2.add(jCheckBoxHab118);
        jCheckBoxHab118.setText("118");

        buttonGroupSencillasP2.add(jCheckBoxHab119);
        jCheckBoxHab119.setText("119");

        buttonGroupDoblesP2.add(jCheckBoxHab120);
        jCheckBoxHab120.setText("120");

        buttonGroupDoblesP2.add(jCheckBoxHab121);
        jCheckBoxHab121.setText("121");

        buttonGroupDoblesP2.add(jCheckBoxHab122);
        jCheckBoxHab122.setText("122");

        buttonGroupDoblesP2.add(jCheckBoxHab123);
        jCheckBoxHab123.setText("123");

        buttonGroupDoblesP2.add(jCheckBoxHab124);
        jCheckBoxHab124.setText("124");

        buttonGroupTripleP2.add(jCheckBoxHab125);
        jCheckBoxHab125.setText("125");

        buttonGroupTripleP2.add(jCheckBoxHab126);
        jCheckBoxHab126.setText("126");

        buttonGroupTripleP2.add(jCheckBoxHab127);
        jCheckBoxHab127.setText("127");

        buttonGroupTripleP2.add(jCheckBoxHab128);
        jCheckBoxHab128.setText("128");

        buttonGroupTripleP2.add(jCheckBoxHab129);
        jCheckBoxHab129.setText("129");

        buttonGroupTripleP2.add(jCheckBoxHab130);
        jCheckBoxHab130.setText("130");

        jLabel1.setText("Costos:");

        jLabel2.setText("Sencilla:");

        jLabel3.setText("Doble:");

        jLabel4.setText("Triple:");

        jLabel5.setText("$500");

        jLabel6.setText("$700");

        jLabel7.setText("$1000");

        jLabel8.setText("Disponible:");

        jPanelDisp.setBackground(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout jPanelDispLayout = new javax.swing.GroupLayout(jPanelDisp);
        jPanelDisp.setLayout(jPanelDispLayout);
        jPanelDispLayout.setHorizontalGroup(
            jPanelDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        jPanelDispLayout.setVerticalGroup(
            jPanelDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanelOcup.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelOcupLayout = new javax.swing.GroupLayout(jPanelOcup);
        jPanelOcup.setLayout(jPanelOcupLayout);
        jPanelOcupLayout.setHorizontalGroup(
            jPanelOcupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        jPanelOcupLayout.setVerticalGroup(
            jPanelOcupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jButtonRentar.setText("Rentar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegresar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPiso2)
                        .addContainerGap(573, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxSencilla2)
                                            .addComponent(jCheckBoxDoble2)
                                            .addComponent(jCheckBoxTriple2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxHab117)
                                            .addComponent(jCheckBoxHab116)
                                            .addComponent(jCheckBoxHab118)))
                                    .addComponent(jCheckBoxHab119))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab123)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab128))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab124)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxHab130)
                                            .addComponent(jCheckBoxHab129)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab121)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab126))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab122)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab127)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRentar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab120)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab125))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPiso1)
                                    .addComponent(jCheckBoxSencilla)
                                    .addComponent(jCheckBoxDoble)
                                    .addComponent(jCheckBoxTriple))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHab104)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab110)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxHab115))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBoxHab103)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBoxHab109)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBoxHab114))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBoxHab102)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBoxHab108)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBoxHab113))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBoxHab101)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBoxHab107)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBoxHab112))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCheckBoxHab106)
                                                    .addComponent(jCheckBoxHab105, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBoxHab111)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)))
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanelDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelOcup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))))
                        .addGap(23, 23, 23))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanelDisp, jPanelOcup});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanelDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBoxHab101)
                                            .addComponent(jCheckBoxHab107)
                                            .addComponent(jCheckBoxHab112)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBoxHab102)
                                            .addComponent(jCheckBoxHab108)
                                            .addComponent(jCheckBoxHab113)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jCheckBoxHab103)
                                                .addComponent(jCheckBoxHab109)
                                                .addComponent(jCheckBoxHab114)
                                                .addComponent(jLabel4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBoxHab104)
                                            .addComponent(jCheckBoxHab110)
                                            .addComponent(jCheckBoxHab115))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jCheckBoxHab111)
                                                    .addComponent(jCheckBoxHab105)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8))))
                                    .addComponent(jPanelOcup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabelPiso2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxSencilla2)
                                    .addComponent(jCheckBoxHab116))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxDoble2)
                                    .addComponent(jCheckBoxHab117))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxTriple2)
                                    .addComponent(jCheckBoxHab118))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxHab119)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMusic)
                            .addComponent(jButtonRegresar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelPiso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxSencilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxDoble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxTriple)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxHab106)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab120)
                            .addComponent(jCheckBoxHab125))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab121)
                            .addComponent(jCheckBoxHab126))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab122)
                            .addComponent(jCheckBoxHab127)
                            .addComponent(jButtonRentar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab123)
                            .addComponent(jCheckBoxHab128))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab124)
                            .addComponent(jCheckBoxHab129))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxHab130)
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanelDisp, jPanelOcup});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSencillaActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(true);
       this.jCheckBoxHab102.setVisible(true);
       this.jCheckBoxHab103.setVisible(true);
       this.jCheckBoxHab104.setVisible(true);
       this.jCheckBoxHab105.setVisible(true);
       this.jCheckBoxHab106.setVisible(true);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
        this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
        this.jCheckBoxHab116.setVisible(false);
       this.jCheckBoxHab117.setVisible(false);
       this.jCheckBoxHab118.setVisible(false);
       this.jCheckBoxHab119.setVisible(false);
       this.jCheckBoxHab120.setVisible(false);
       this.jCheckBoxHab121.setVisible(false);
       this.jCheckBoxHab122.setVisible(false);
       this.jCheckBoxHab123.setVisible(false);
       this.jCheckBoxHab124.setVisible(false);
       this.jCheckBoxHab125.setVisible(false);
       this.jCheckBoxHab126.setVisible(false);
       this.jCheckBoxHab127.setVisible(false);
       this.jCheckBoxHab128.setVisible(false);
       this.jCheckBoxHab129.setVisible(false);
       this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxSencillaActionPerformed

    private void jCheckBoxDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDobleActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(true);
       this.jCheckBoxHab108.setVisible(true);
       this.jCheckBoxHab109.setVisible(true);
       this.jCheckBoxHab110.setVisible(true);
       this.jCheckBoxHab111.setVisible(true);
       this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
        this.jCheckBoxHab116.setVisible(false);
       this.jCheckBoxHab117.setVisible(false);
       this.jCheckBoxHab118.setVisible(false);
       this.jCheckBoxHab119.setVisible(false);
       this.jCheckBoxHab120.setVisible(false);
       this.jCheckBoxHab121.setVisible(false);
       this.jCheckBoxHab122.setVisible(false);
       this.jCheckBoxHab123.setVisible(false);
       this.jCheckBoxHab124.setVisible(false);
       this.jCheckBoxHab125.setVisible(false);
       this.jCheckBoxHab126.setVisible(false);
       this.jCheckBoxHab127.setVisible(false);
       this.jCheckBoxHab128.setVisible(false);
       this.jCheckBoxHab129.setVisible(false);
       this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxDobleActionPerformed

    private void jCheckBoxTripleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTripleActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
       this.jCheckBoxHab112.setVisible(true);
       this.jCheckBoxHab113.setVisible(true);
       this.jCheckBoxHab114.setVisible(true);
       this.jCheckBoxHab115.setVisible(true);
       this.jCheckBoxHab116.setVisible(false);
       this.jCheckBoxHab117.setVisible(false);
       this.jCheckBoxHab118.setVisible(false);
       this.jCheckBoxHab119.setVisible(false);
       this.jCheckBoxHab120.setVisible(false);
       this.jCheckBoxHab121.setVisible(false);
       this.jCheckBoxHab122.setVisible(false);
       this.jCheckBoxHab123.setVisible(false);
       this.jCheckBoxHab124.setVisible(false);
       this.jCheckBoxHab125.setVisible(false);
       this.jCheckBoxHab126.setVisible(false);
       this.jCheckBoxHab127.setVisible(false);
       this.jCheckBoxHab128.setVisible(false);
       this.jCheckBoxHab129.setVisible(false);
       this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxTripleActionPerformed

    private void jCheckBoxDoble2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDoble2ActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
       this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
       this.jCheckBoxHab116.setVisible(false);
       this.jCheckBoxHab117.setVisible(false);
       this.jCheckBoxHab118.setVisible(false);
       this.jCheckBoxHab119.setVisible(false);
       this.jCheckBoxHab120.setVisible(true);
       this.jCheckBoxHab121.setVisible(true);
       this.jCheckBoxHab122.setVisible(true);
       this.jCheckBoxHab123.setVisible(true);
       this.jCheckBoxHab124.setVisible(true);
       this.jCheckBoxHab125.setVisible(false);
       this.jCheckBoxHab126.setVisible(false);
       this.jCheckBoxHab127.setVisible(false);
       this.jCheckBoxHab128.setVisible(false);
       this.jCheckBoxHab129.setVisible(false);
       this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxDoble2ActionPerformed

    private void jCheckBoxSencilla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSencilla2ActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
       this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
       this.jCheckBoxHab116.setVisible(true);
       this.jCheckBoxHab117.setVisible(true);
       this.jCheckBoxHab118.setVisible(true);
       this.jCheckBoxHab119.setVisible(true);
       this.jCheckBoxHab120.setVisible(false);
       this.jCheckBoxHab121.setVisible(false);
       this.jCheckBoxHab122.setVisible(false);
       this.jCheckBoxHab123.setVisible(false);
       this.jCheckBoxHab124.setVisible(false);
       this.jCheckBoxHab125.setVisible(false);
       this.jCheckBoxHab126.setVisible(false);
       this.jCheckBoxHab127.setVisible(false);
       this.jCheckBoxHab128.setVisible(false);
       this.jCheckBoxHab129.setVisible(false);
       this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxSencilla2ActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal abrir=new MenuPrincipal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jCheckBoxTriple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTriple2ActionPerformed
        // TODO add your handling code here:
       this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
       this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
       this.jCheckBoxHab116.setVisible(false);
       this.jCheckBoxHab117.setVisible(false);
       this.jCheckBoxHab118.setVisible(false);
       this.jCheckBoxHab119.setVisible(false);
       this.jCheckBoxHab120.setVisible(false);
       this.jCheckBoxHab121.setVisible(false);
       this.jCheckBoxHab122.setVisible(false);
       this.jCheckBoxHab123.setVisible(false);
       this.jCheckBoxHab124.setVisible(false);
       this.jCheckBoxHab125.setVisible(true);
       this.jCheckBoxHab126.setVisible(true);
       this.jCheckBoxHab127.setVisible(true);
       this.jCheckBoxHab128.setVisible(true);
       this.jCheckBoxHab129.setVisible(true);
       this.jCheckBoxHab130.setVisible(true);
    }//GEN-LAST:event_jCheckBoxTriple2ActionPerformed

    private void jCheckBoxHab106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHab106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHab106ActionPerformed

    private void jCheckBoxHab101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHab101ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jCheckBoxHab101ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDobleP1;
    private javax.swing.ButtonGroup buttonGroupDoblesP2;
    private javax.swing.ButtonGroup buttonGroupSencillasP1;
    private javax.swing.ButtonGroup buttonGroupSencillasP2;
    private javax.swing.ButtonGroup buttonGroupTiposP1;
    private javax.swing.ButtonGroup buttonGroupTiposP2;
    private javax.swing.ButtonGroup buttonGroupTripleP1;
    private javax.swing.ButtonGroup buttonGroupTripleP2;
    private javax.swing.JButton jButtonMusic;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonRentar;
    private javax.swing.JCheckBox jCheckBoxDoble;
    private javax.swing.JCheckBox jCheckBoxDoble2;
    private javax.swing.JCheckBox jCheckBoxHab101;
    private javax.swing.JCheckBox jCheckBoxHab102;
    private javax.swing.JCheckBox jCheckBoxHab103;
    private javax.swing.JCheckBox jCheckBoxHab104;
    private javax.swing.JCheckBox jCheckBoxHab105;
    private javax.swing.JCheckBox jCheckBoxHab106;
    private javax.swing.JCheckBox jCheckBoxHab107;
    private javax.swing.JCheckBox jCheckBoxHab108;
    private javax.swing.JCheckBox jCheckBoxHab109;
    private javax.swing.JCheckBox jCheckBoxHab110;
    private javax.swing.JCheckBox jCheckBoxHab111;
    private javax.swing.JCheckBox jCheckBoxHab112;
    private javax.swing.JCheckBox jCheckBoxHab113;
    private javax.swing.JCheckBox jCheckBoxHab114;
    private javax.swing.JCheckBox jCheckBoxHab115;
    private javax.swing.JCheckBox jCheckBoxHab116;
    private javax.swing.JCheckBox jCheckBoxHab117;
    private javax.swing.JCheckBox jCheckBoxHab118;
    private javax.swing.JCheckBox jCheckBoxHab119;
    private javax.swing.JCheckBox jCheckBoxHab120;
    private javax.swing.JCheckBox jCheckBoxHab121;
    private javax.swing.JCheckBox jCheckBoxHab122;
    private javax.swing.JCheckBox jCheckBoxHab123;
    private javax.swing.JCheckBox jCheckBoxHab124;
    private javax.swing.JCheckBox jCheckBoxHab125;
    private javax.swing.JCheckBox jCheckBoxHab126;
    private javax.swing.JCheckBox jCheckBoxHab127;
    private javax.swing.JCheckBox jCheckBoxHab128;
    private javax.swing.JCheckBox jCheckBoxHab129;
    private javax.swing.JCheckBox jCheckBoxHab130;
    private javax.swing.JCheckBox jCheckBoxSencilla;
    private javax.swing.JCheckBox jCheckBoxSencilla2;
    private javax.swing.JCheckBox jCheckBoxTriple;
    private javax.swing.JCheckBox jCheckBoxTriple2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPiso1;
    private javax.swing.JLabel jLabelPiso2;
    private javax.swing.JPanel jPanelDisp;
    private javax.swing.JPanel jPanelOcup;
    // End of variables declaration//GEN-END:variables
   /*class FondoPanel extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){
           imagen= new ImageIcon(getClass().getResource("src/imagenes/fondo.jpg")).getImage();
           g.drawImage(imagen, 0, 0, getWidth(),getHeight(), this);
           setOpaque(false);
           super.paint(g);
        }
    }*/
    
}

