/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author Miguel
 */
public class Check_Out extends javax.swing.JFrame {

    /**
     * Creates new form Check_Out
     */
    public Check_Out() {
        initComponents();
         this.jCheckBoxHab101.setVisible(false);
       this.jCheckBoxHab102.setVisible(false);
       this.jCheckBoxHab103.setVisible(false);
       this.jCheckBoxHab104.setVisible(false);
       this.jCheckBoxHab105.setVisible(false);
       this.jCheckBoxHab106.setVisible(false);
       this.jCheckBoxHab107.setVisible(false);
       this.jCheckBoxHab108.setVisible(false);
       this.jCheckBoxHab109.setVisible(false);
       this.jCheckBoxHab110.setVisible(false);
       this.jCheckBoxHab111.setVisible(false);
       this.jCheckBoxHab112.setVisible(false);
       this.jCheckBoxHab113.setVisible(false);
       this.jCheckBoxHab114.setVisible(false);
       this.jCheckBoxHab115.setVisible(false);
       this.jCheckBoxHab116.setVisible(false);
       this.jCheckBoxHab117.setVisible(false);
       this.jCheckBoxHab118.setVisible(false);
       this.jCheckBoxHab119.setVisible(false);
       this.jCheckBoxHab120.setVisible(false);
       this.jCheckBoxHab121.setVisible(false);
       this.jCheckBoxHab122.setVisible(false);
       this.jCheckBoxHab123.setVisible(false);
       this.jCheckBoxHab124.setVisible(false);
       this.jCheckBoxHab125.setVisible(false);
       this.jCheckBoxHab126.setVisible(false);
       this.jCheckBoxHab127.setVisible(false);
       this.jCheckBoxHab128.setVisible(false);
       this.jCheckBoxHab129.setVisible(false);
       this.jCheckBoxHab130.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTiposP1 = new javax.swing.ButtonGroup();
        buttonGroupSencillasP1 = new javax.swing.ButtonGroup();
        buttonGroupDobleP1 = new javax.swing.ButtonGroup();
        buttonGroupTripleP1 = new javax.swing.ButtonGroup();
        buttonGroupTiposP2 = new javax.swing.ButtonGroup();
        buttonGroupSencillasP2 = new javax.swing.ButtonGroup();
        buttonGroupDoblesP2 = new javax.swing.ButtonGroup();
        buttonGroupTripleP2 = new javax.swing.ButtonGroup();
        jCheckBoxHab126 = new javax.swing.JCheckBox();
        jCheckBoxHab127 = new javax.swing.JCheckBox();
        jCheckBoxHab128 = new javax.swing.JCheckBox();
        jCheckBoxHab129 = new javax.swing.JCheckBox();
        jCheckBoxHab130 = new javax.swing.JCheckBox();
        jLabelPiso2 = new javax.swing.JLabel();
        jCheckBoxSencilla = new javax.swing.JCheckBox();
        jCheckBoxDoble = new javax.swing.JCheckBox();
        jCheckBoxTriple = new javax.swing.JCheckBox();
        jCheckBoxSencilla2 = new javax.swing.JCheckBox();
        jCheckBoxDoble2 = new javax.swing.JCheckBox();
        jCheckBoxTriple2 = new javax.swing.JCheckBox();
        jCheckBoxHab101 = new javax.swing.JCheckBox();
        jCheckBoxHab102 = new javax.swing.JCheckBox();
        jCheckBoxHab103 = new javax.swing.JCheckBox();
        jLabelPiso1 = new javax.swing.JLabel();
        jCheckBoxHab104 = new javax.swing.JCheckBox();
        jCheckBoxHab105 = new javax.swing.JCheckBox();
        jCheckBoxHab106 = new javax.swing.JCheckBox();
        jCheckBoxHab107 = new javax.swing.JCheckBox();
        jCheckBoxHab108 = new javax.swing.JCheckBox();
        jCheckBoxHab109 = new javax.swing.JCheckBox();
        jCheckBoxHab110 = new javax.swing.JCheckBox();
        jCheckBoxHab111 = new javax.swing.JCheckBox();
        jCheckBoxHab112 = new javax.swing.JCheckBox();
        jCheckBoxHab113 = new javax.swing.JCheckBox();
        jCheckBoxHab114 = new javax.swing.JCheckBox();
        jCheckBoxHab115 = new javax.swing.JCheckBox();
        jButtonMusic = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jCheckBoxHab116 = new javax.swing.JCheckBox();
        jCheckBoxHab117 = new javax.swing.JCheckBox();
        jCheckBoxHab118 = new javax.swing.JCheckBox();
        jCheckBoxHab119 = new javax.swing.JCheckBox();
        jCheckBoxHab120 = new javax.swing.JCheckBox();
        jCheckBoxHab121 = new javax.swing.JCheckBox();
        jCheckBoxHab122 = new javax.swing.JCheckBox();
        jCheckBoxHab123 = new javax.swing.JCheckBox();
        jCheckBoxHab124 = new javax.swing.JCheckBox();
        jCheckBoxHab125 = new javax.swing.JCheckBox();
        jButtonEntregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBoxHab126.setText("126");
        jCheckBoxHab126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHab126ActionPerformed(evt);
            }
        });

        jCheckBoxHab127.setText("127");

        jCheckBoxHab128.setText("128");

        jCheckBoxHab129.setText("129");

        jCheckBoxHab130.setText("130");

        jLabelPiso2.setText("Piso 2");

        buttonGroupTiposP1.add(jCheckBoxSencilla);
        jCheckBoxSencilla.setText("Sencilla");
        jCheckBoxSencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSencillaActionPerformed(evt);
            }
        });

        buttonGroupTiposP1.add(jCheckBoxDoble);
        jCheckBoxDoble.setText("Doble");
        jCheckBoxDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDobleActionPerformed(evt);
            }
        });

        buttonGroupTiposP1.add(jCheckBoxTriple);
        jCheckBoxTriple.setText("Triple");
        jCheckBoxTriple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTripleActionPerformed(evt);
            }
        });

        buttonGroupTiposP2.add(jCheckBoxSencilla2);
        jCheckBoxSencilla2.setText("Sencilla");
        jCheckBoxSencilla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSencilla2ActionPerformed(evt);
            }
        });

        buttonGroupTiposP2.add(jCheckBoxDoble2);
        jCheckBoxDoble2.setText("Doble");
        jCheckBoxDoble2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDoble2ActionPerformed(evt);
            }
        });

        buttonGroupTiposP2.add(jCheckBoxTriple2);
        jCheckBoxTriple2.setText("Triple");
        jCheckBoxTriple2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTriple2ActionPerformed(evt);
            }
        });

        buttonGroupSencillasP1.add(jCheckBoxHab101);
        jCheckBoxHab101.setText("101");

        buttonGroupSencillasP1.add(jCheckBoxHab102);
        jCheckBoxHab102.setText("102");

        buttonGroupSencillasP1.add(jCheckBoxHab103);
        jCheckBoxHab103.setText("103");

        jLabelPiso1.setText("Piso 1");

        buttonGroupSencillasP1.add(jCheckBoxHab104);
        jCheckBoxHab104.setText("104");

        buttonGroupSencillasP1.add(jCheckBoxHab105);
        jCheckBoxHab105.setText("105");

        buttonGroupSencillasP1.add(jCheckBoxHab106);
        jCheckBoxHab106.setText("106");

        buttonGroupDobleP1.add(jCheckBoxHab107);
        jCheckBoxHab107.setText("107");

        buttonGroupDobleP1.add(jCheckBoxHab108);
        jCheckBoxHab108.setText("108");

        buttonGroupDobleP1.add(jCheckBoxHab109);
        jCheckBoxHab109.setText("109");

        buttonGroupDobleP1.add(jCheckBoxHab110);
        jCheckBoxHab110.setText("110");

        buttonGroupDobleP1.add(jCheckBoxHab111);
        jCheckBoxHab111.setText("111");

        buttonGroupTripleP1.add(jCheckBoxHab112);
        jCheckBoxHab112.setText("112");

        buttonGroupTripleP1.add(jCheckBoxHab113);
        jCheckBoxHab113.setText("113");

        buttonGroupTripleP1.add(jCheckBoxHab114);
        jCheckBoxHab114.setText("114");

        buttonGroupTripleP1.add(jCheckBoxHab115);
        jCheckBoxHab115.setText("115");

        jButtonMusic.setText("Music");

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jCheckBoxHab116.setText("116");

        jCheckBoxHab117.setText("117");

        jCheckBoxHab118.setText("118");

        jCheckBoxHab119.setText("119");

        jCheckBoxHab120.setText("120");

        jCheckBoxHab121.setText("121");

        jCheckBoxHab122.setText("122");

        jCheckBoxHab123.setText("123");

        jCheckBoxHab124.setText("124");

        jCheckBoxHab125.setText("125");

        jButtonEntregar.setText("Entregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab103)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab109)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab114))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab102)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab108)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab113))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab105)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab111))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab101)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab107)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab112))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab106)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                                .addComponent(jButtonEntregar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPiso1)
                            .addComponent(jCheckBoxSencilla)
                            .addComponent(jCheckBoxDoble)
                            .addComponent(jCheckBoxTriple))
                        .addGap(40, 40, 40)
                        .addComponent(jCheckBoxHab104)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxHab110)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxHab115))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxSencilla2)
                                    .addComponent(jCheckBoxDoble2)
                                    .addComponent(jCheckBoxTriple2)))
                            .addComponent(jLabelPiso2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxHab119)
                                .addComponent(jCheckBoxHab117, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jCheckBoxHab118)
                            .addComponent(jCheckBoxHab116))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab123)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab128))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab124)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxHab130)
                                    .addComponent(jCheckBoxHab129)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab122)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab127))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab121)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab126))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHab120)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHab125)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabelPiso2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxSencilla2)
                                    .addComponent(jCheckBoxHab116))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxDoble2)
                                    .addComponent(jCheckBoxHab117))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxTriple2)
                                    .addComponent(jCheckBoxHab118)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxHab101)
                                    .addComponent(jCheckBoxHab107)
                                    .addComponent(jCheckBoxHab112))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxHab102)
                                    .addComponent(jCheckBoxHab108)
                                    .addComponent(jCheckBoxHab113))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxHab103)
                                    .addComponent(jCheckBoxHab109)
                                    .addComponent(jCheckBoxHab114))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxHab104)
                                    .addComponent(jCheckBoxHab110)
                                    .addComponent(jCheckBoxHab115))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxHab111)
                                    .addComponent(jCheckBoxHab105))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxHab106)
                                    .addComponent(jButtonEntregar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxHab119)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMusic)
                            .addComponent(jButtonRegresar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelPiso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxSencilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxDoble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxTriple)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab120)
                            .addComponent(jCheckBoxHab125))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab121)
                            .addComponent(jCheckBoxHab126))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab122)
                            .addComponent(jCheckBoxHab127))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab123)
                            .addComponent(jCheckBoxHab128))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxHab124)
                            .addComponent(jCheckBoxHab129))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxHab130)
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSencillaActionPerformed
        // TODO add your handling code here:
        this.jCheckBoxHab101.setVisible(true);
        this.jCheckBoxHab102.setVisible(true);
        this.jCheckBoxHab103.setVisible(true);
        this.jCheckBoxHab104.setVisible(true);
        this.jCheckBoxHab105.setVisible(true);
        this.jCheckBoxHab106.setVisible(true);
        this.jCheckBoxHab107.setVisible(false);
        this.jCheckBoxHab108.setVisible(false);
        this.jCheckBoxHab109.setVisible(false);
        this.jCheckBoxHab110.setVisible(false);
        this.jCheckBoxHab111.setVisible(false);
        this.jCheckBoxHab112.setVisible(false);
        this.jCheckBoxHab113.setVisible(false);
        this.jCheckBoxHab114.setVisible(false);
        this.jCheckBoxHab115.setVisible(false);
        this.jCheckBoxHab116.setVisible(false);
        this.jCheckBoxHab117.setVisible(false);
        this.jCheckBoxHab118.setVisible(false);
        this.jCheckBoxHab119.setVisible(false);
        this.jCheckBoxHab120.setVisible(false);
        this.jCheckBoxHab121.setVisible(false);
        this.jCheckBoxHab122.setVisible(false);
        this.jCheckBoxHab123.setVisible(false);
        this.jCheckBoxHab124.setVisible(false);
        this.jCheckBoxHab125.setVisible(false);
        this.jCheckBoxHab126.setVisible(false);
        this.jCheckBoxHab127.setVisible(false);
        this.jCheckBoxHab128.setVisible(false);
        this.jCheckBoxHab129.setVisible(false);
        this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxSencillaActionPerformed

    private void jCheckBoxDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDobleActionPerformed
        // TODO add your handling code here:
        this.jCheckBoxHab101.setVisible(false);
        this.jCheckBoxHab102.setVisible(false);
        this.jCheckBoxHab103.setVisible(false);
        this.jCheckBoxHab104.setVisible(false);
        this.jCheckBoxHab105.setVisible(false);
        this.jCheckBoxHab106.setVisible(false);
        this.jCheckBoxHab107.setVisible(true);
        this.jCheckBoxHab108.setVisible(true);
        this.jCheckBoxHab109.setVisible(true);
        this.jCheckBoxHab110.setVisible(true);
        this.jCheckBoxHab111.setVisible(true);
        this.jCheckBoxHab112.setVisible(false);
        this.jCheckBoxHab113.setVisible(false);
        this.jCheckBoxHab114.setVisible(false);
        this.jCheckBoxHab115.setVisible(false);
        this.jCheckBoxHab116.setVisible(false);
        this.jCheckBoxHab117.setVisible(false);
        this.jCheckBoxHab118.setVisible(false);
        this.jCheckBoxHab119.setVisible(false);
        this.jCheckBoxHab120.setVisible(false);
        this.jCheckBoxHab121.setVisible(false);
        this.jCheckBoxHab122.setVisible(false);
        this.jCheckBoxHab123.setVisible(false);
        this.jCheckBoxHab124.setVisible(false);
        this.jCheckBoxHab125.setVisible(false);
        this.jCheckBoxHab126.setVisible(false);
        this.jCheckBoxHab127.setVisible(false);
        this.jCheckBoxHab128.setVisible(false);
        this.jCheckBoxHab129.setVisible(false);
        this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxDobleActionPerformed

    private void jCheckBoxTripleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTripleActionPerformed
        // TODO add your handling code here:
        this.jCheckBoxHab101.setVisible(false);
        this.jCheckBoxHab102.setVisible(false);
        this.jCheckBoxHab103.setVisible(false);
        this.jCheckBoxHab104.setVisible(false);
        this.jCheckBoxHab105.setVisible(false);
        this.jCheckBoxHab106.setVisible(false);
        this.jCheckBoxHab107.setVisible(false);
        this.jCheckBoxHab108.setVisible(false);
        this.jCheckBoxHab109.setVisible(false);
        this.jCheckBoxHab110.setVisible(false);
        this.jCheckBoxHab111.setVisible(false);
        this.jCheckBoxHab112.setVisible(true);
        this.jCheckBoxHab113.setVisible(true);
        this.jCheckBoxHab114.setVisible(true);
        this.jCheckBoxHab115.setVisible(true);
        this.jCheckBoxHab116.setVisible(false);
        this.jCheckBoxHab117.setVisible(false);
        this.jCheckBoxHab118.setVisible(false);
        this.jCheckBoxHab119.setVisible(false);
        this.jCheckBoxHab120.setVisible(false);
        this.jCheckBoxHab121.setVisible(false);
        this.jCheckBoxHab122.setVisible(false);
        this.jCheckBoxHab123.setVisible(false);
        this.jCheckBoxHab124.setVisible(false);
        this.jCheckBoxHab125.setVisible(false);
        this.jCheckBoxHab126.setVisible(false);
        this.jCheckBoxHab127.setVisible(false);
        this.jCheckBoxHab128.setVisible(false);
        this.jCheckBoxHab129.setVisible(false);
        this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxTripleActionPerformed

    private void jCheckBoxSencilla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSencilla2ActionPerformed
        // TODO add your handling code here:
        this.jCheckBoxHab101.setVisible(false);
        this.jCheckBoxHab102.setVisible(false);
        this.jCheckBoxHab103.setVisible(false);
        this.jCheckBoxHab104.setVisible(false);
        this.jCheckBoxHab105.setVisible(false);
        this.jCheckBoxHab106.setVisible(false);
        this.jCheckBoxHab107.setVisible(false);
        this.jCheckBoxHab108.setVisible(false);
        this.jCheckBoxHab109.setVisible(false);
        this.jCheckBoxHab110.setVisible(false);
        this.jCheckBoxHab111.setVisible(false);
        this.jCheckBoxHab112.setVisible(false);
        this.jCheckBoxHab113.setVisible(false);
        this.jCheckBoxHab114.setVisible(false);
        this.jCheckBoxHab115.setVisible(false);
        this.jCheckBoxHab116.setVisible(true);
        this.jCheckBoxHab117.setVisible(true);
        this.jCheckBoxHab118.setVisible(true);
        this.jCheckBoxHab119.setVisible(true);
        this.jCheckBoxHab120.setVisible(false);
        this.jCheckBoxHab121.setVisible(false);
        this.jCheckBoxHab122.setVisible(false);
        this.jCheckBoxHab123.setVisible(false);
        this.jCheckBoxHab124.setVisible(false);
        this.jCheckBoxHab125.setVisible(false);
        this.jCheckBoxHab126.setVisible(false);
        this.jCheckBoxHab127.setVisible(false);
        this.jCheckBoxHab128.setVisible(false);
        this.jCheckBoxHab129.setVisible(false);
        this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxSencilla2ActionPerformed

    private void jCheckBoxDoble2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDoble2ActionPerformed
        // TODO add your handling code here:
        this.jCheckBoxHab101.setVisible(false);
        this.jCheckBoxHab102.setVisible(false);
        this.jCheckBoxHab103.setVisible(false);
        this.jCheckBoxHab104.setVisible(false);
        this.jCheckBoxHab105.setVisible(false);
        this.jCheckBoxHab106.setVisible(false);
        this.jCheckBoxHab107.setVisible(false);
        this.jCheckBoxHab108.setVisible(false);
        this.jCheckBoxHab109.setVisible(false);
        this.jCheckBoxHab110.setVisible(false);
        this.jCheckBoxHab111.setVisible(false);
        this.jCheckBoxHab112.setVisible(false);
        this.jCheckBoxHab113.setVisible(false);
        this.jCheckBoxHab114.setVisible(false);
        this.jCheckBoxHab115.setVisible(false);
        this.jCheckBoxHab116.setVisible(false);
        this.jCheckBoxHab117.setVisible(false);
        this.jCheckBoxHab118.setVisible(false);
        this.jCheckBoxHab119.setVisible(false);
        this.jCheckBoxHab120.setVisible(true);
        this.jCheckBoxHab121.setVisible(true);
        this.jCheckBoxHab122.setVisible(true);
        this.jCheckBoxHab123.setVisible(true);
        this.jCheckBoxHab124.setVisible(true);
        this.jCheckBoxHab125.setVisible(false);
        this.jCheckBoxHab126.setVisible(false);
        this.jCheckBoxHab127.setVisible(false);
        this.jCheckBoxHab128.setVisible(false);
        this.jCheckBoxHab129.setVisible(false);
        this.jCheckBoxHab130.setVisible(false);
    }//GEN-LAST:event_jCheckBoxDoble2ActionPerformed

    private void jCheckBoxTriple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTriple2ActionPerformed
        // TODO add your handling code here:
        this.jCheckBoxHab101.setVisible(false);
        this.jCheckBoxHab102.setVisible(false);
        this.jCheckBoxHab103.setVisible(false);
        this.jCheckBoxHab104.setVisible(false);
        this.jCheckBoxHab105.setVisible(false);
        this.jCheckBoxHab106.setVisible(false);
        this.jCheckBoxHab107.setVisible(false);
        this.jCheckBoxHab108.setVisible(false);
        this.jCheckBoxHab109.setVisible(false);
        this.jCheckBoxHab110.setVisible(false);
        this.jCheckBoxHab111.setVisible(false);
        this.jCheckBoxHab112.setVisible(false);
        this.jCheckBoxHab113.setVisible(false);
        this.jCheckBoxHab114.setVisible(false);
        this.jCheckBoxHab115.setVisible(false);
        this.jCheckBoxHab116.setVisible(false);
        this.jCheckBoxHab117.setVisible(false);
        this.jCheckBoxHab118.setVisible(false);
        this.jCheckBoxHab119.setVisible(false);
        this.jCheckBoxHab120.setVisible(false);
        this.jCheckBoxHab121.setVisible(false);
        this.jCheckBoxHab122.setVisible(false);
        this.jCheckBoxHab123.setVisible(false);
        this.jCheckBoxHab124.setVisible(false);
        this.jCheckBoxHab125.setVisible(true);
        this.jCheckBoxHab126.setVisible(true);
        this.jCheckBoxHab127.setVisible(true);
        this.jCheckBoxHab128.setVisible(true);
        this.jCheckBoxHab129.setVisible(true);
        this.jCheckBoxHab130.setVisible(true);
    }//GEN-LAST:event_jCheckBoxTriple2ActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal abrir=new MenuPrincipal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jCheckBoxHab126ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHab126ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHab126ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_Out().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDobleP1;
    private javax.swing.ButtonGroup buttonGroupDoblesP2;
    private javax.swing.ButtonGroup buttonGroupSencillasP1;
    private javax.swing.ButtonGroup buttonGroupSencillasP2;
    private javax.swing.ButtonGroup buttonGroupTiposP1;
    private javax.swing.ButtonGroup buttonGroupTiposP2;
    private javax.swing.ButtonGroup buttonGroupTripleP1;
    private javax.swing.ButtonGroup buttonGroupTripleP2;
    private javax.swing.JButton jButtonEntregar;
    private javax.swing.JButton jButtonMusic;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JCheckBox jCheckBoxDoble;
    private javax.swing.JCheckBox jCheckBoxDoble2;
    private javax.swing.JCheckBox jCheckBoxHab101;
    private javax.swing.JCheckBox jCheckBoxHab102;
    private javax.swing.JCheckBox jCheckBoxHab103;
    private javax.swing.JCheckBox jCheckBoxHab104;
    private javax.swing.JCheckBox jCheckBoxHab105;
    private javax.swing.JCheckBox jCheckBoxHab106;
    private javax.swing.JCheckBox jCheckBoxHab107;
    private javax.swing.JCheckBox jCheckBoxHab108;
    private javax.swing.JCheckBox jCheckBoxHab109;
    private javax.swing.JCheckBox jCheckBoxHab110;
    private javax.swing.JCheckBox jCheckBoxHab111;
    private javax.swing.JCheckBox jCheckBoxHab112;
    private javax.swing.JCheckBox jCheckBoxHab113;
    private javax.swing.JCheckBox jCheckBoxHab114;
    private javax.swing.JCheckBox jCheckBoxHab115;
    private javax.swing.JCheckBox jCheckBoxHab116;
    private javax.swing.JCheckBox jCheckBoxHab117;
    private javax.swing.JCheckBox jCheckBoxHab118;
    private javax.swing.JCheckBox jCheckBoxHab119;
    private javax.swing.JCheckBox jCheckBoxHab120;
    private javax.swing.JCheckBox jCheckBoxHab121;
    private javax.swing.JCheckBox jCheckBoxHab122;
    private javax.swing.JCheckBox jCheckBoxHab123;
    private javax.swing.JCheckBox jCheckBoxHab124;
    private javax.swing.JCheckBox jCheckBoxHab125;
    private javax.swing.JCheckBox jCheckBoxHab126;
    private javax.swing.JCheckBox jCheckBoxHab127;
    private javax.swing.JCheckBox jCheckBoxHab128;
    private javax.swing.JCheckBox jCheckBoxHab129;
    private javax.swing.JCheckBox jCheckBoxHab130;
    private javax.swing.JCheckBox jCheckBoxSencilla;
    private javax.swing.JCheckBox jCheckBoxSencilla2;
    private javax.swing.JCheckBox jCheckBoxTriple;
    private javax.swing.JCheckBox jCheckBoxTriple2;
    private javax.swing.JLabel jLabelPiso1;
    private javax.swing.JLabel jLabelPiso2;
    // End of variables declaration//GEN-END:variables
}
